live_config_reload = true
import = ["/home/fin/.config/alacritty/rose-pine-dawn.toml"]
#import = ["/home/fin/.config/alacritty/rose-pine.toml"]


[env]
TERM = "alacritty"

[window]
decorations     = "none"
dynamic_padding = false
dynamic_title   = true
opacity         = 1.0
startup_mode    = "Maximized"
title           = "Alacritty"

[window.dimensions]
columns = 0
lines   = 0

[window.padding]
x = 12
y = 12

[scrolling]
history = 12000

[font]
builtin_box_drawing = false
size                = 14
[font.bold]
family = "Iosevka"
style  = "Bold"

[font.bold_italic]
family = "Iosevka"
style  = "Bold Italic"

[font.glyph_offset]
x = 0
y = 0

[font.italic]
family = "Iosevka"
style  = "Italic"

[font.normal]
family = "Iosevka"
style  = "Regular"

[font.offset]
x = 0
y = 0
