search_paths = [
    '/Code/220905 Postgres Flask',
    '/Code/Adafruit_AMG88xx',
    '/Code/Adafruit-Feather-ESP32-S3-PCB',
    '/Code/aiiDocs',
    '/Code/AII Projects',
    '/Code/aiOrg',
    '/Code/ai-stack',
    '/Code/avenue-api',
    '/Code/avenuecicd',
    '/Code/avenueIntelligence Logseq',
    '/Code/avenueOrg',
    '/Code/avenuerust',
    '/Code/baremetalVirtman',
    '/Code/Cannabisystem',
    '/Code/cicd-flask-oracle',
    '/Code/clonebuddy',
    '/Code/ESP32',
    '/Code/ESP32-OTA',
    '/Code/esp32 wifi',
    '/Code/finsarduinolibraries',
    '/Code/flask-datta-able',
    '/Code/flaskui',
    '/Code/footstep-helium-node',
    '/Code/footstep-kicad',
    '/Code/footstep-lora-gateway-sx126x',
    '/Code/footstep-lora-node',
    '/Code/go-avenue-genart',
    '/Code/gofluxcsv',
    '/Code/go-rosepine-genart',
    '/Code/gpt4all',
    '/Code/helium-chirpstack-community',
    '/Code/heliumVIPConsoleFunctions',
    '/Code/heltecwslv3',
    '/Code/heltecwslv3.bk',
    '/Code/huggingface',
    '/Code/id_rsa_gitlab.pub',
    '/Code/InfluxDB-ChartJS-Tutorial',
    '/Code/iot-server',
    '/Code/IWR6843-Read-Data-Python-MMWAVE-SDK',
    '/Code/jekyll',
    '/Code/JS Webapp demo project',
    '/Code/Jupyter',
    '/Code/jupyterreports',
    '/Code/kicad',
    '/Code/lapa',
    '/Code/linuxDashboard',
    '/Code/llama.cpp',
    '/Code/llm',
    '/Code/MAC-S3',
    '/Code/mern-cqc',
    '/Code/MERN CQC App',
    '/Code/modularcontroller',
    '/Code/MP-GPT',
    '/Code/mpgpt',
    '/Code/nix',
    '/Code/nodeMCUclimateControl',
    '/Code/nomic',
    '/Code/org',
    '/Code/pagoda',
    '/Code/People-Counting-in-Real-Time',
    '/Code/Picoclick-C3',
    '/Code/pymmw',
    '/Code/pymmWave',
    '/Code/pyrodetectors',
    '/Code/qmk_firmware',
    '/Code/qmk_firmware.2',
    '/Code/README.md',
    '/Code/rose-pine-logseq',
    '/Code/scripts',
    '/Code/seleniumScrape',
    '/Code/smallsolutions',
    '/Code/smallSolutions Logseq',
    '/Code/syncthingAutomerge',
    '/Code/t3test',
    '/Code/text-generation-webui',
    '/Code/traffic-monitor',
    '/Code/virt-manager_baremetal-passthrough',
    '/Code/website220628',
]
